#ifndef _SPLOADER_LOADER_H
#define _SPLOADER_LOADER_H

#define LOADER_EARLY_SEGMENT 0x7C0
#define LOADER_EARLY_ADDRESS 0x200

#define LOADER_GDT_SEGMENT 0x01100
#define LOADER_GDT_ADDRESS 0x11000


#endif