
import sys

if __name__ == "__main__":

    if len(sys.argv) != 2:
        sys.exit(1)

    names = []

    print """
// THIS FILE WAS GENERATED BY mksymtab.py!
// DO NOT EDIT THIS FILE

.globl SYMBOL_TABLE
.data

SYMBOL_TABLE:
    .long (__symbols_end - __symbols) / 8
    .long __symbols
__symbols:"""

    with open(sys.argv[1], "r") as f:
        i = 0
        for line in f:
            tokens = line.split()
            if tokens[1].lower() == "t":
                print "    .long __name_%d" % i			
                print "    .long 0x%s" % tokens[0]
                names.append(tokens[2])
                i += 1
        print "__symbols_end:"

    for i, name in enumerate(names):
        print "__name_%d:" % i
        print '    .asciz "%s"' % name
